// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.res.mjs";
import * as Login from "./Login.res.mjs";
import * as Signup from "./Signup.res.mjs";
import * as LoginContext from "./LoginContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  if (match) {
    switch (match.hd) {
      case "login" :
          tmp = match.tl ? JsxRuntime.jsx(Home.make, {}) : JsxRuntime.jsx(Login.make, {});
          break;
      case "signup" :
          tmp = match.tl ? JsxRuntime.jsx(Home.make, {}) : JsxRuntime.jsx(Signup.make, {});
          break;
      default:
        tmp = JsxRuntime.jsx(Home.make, {});
    }
  } else {
    tmp = JsxRuntime.jsx(Home.make, {});
  }
  return JsxRuntime.jsx(LoginContext.DefaultProvider.make, {
              children: tmp
            });
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
