// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as WorkersData from "./data/WorkersData.res.mjs";
import * as ContentModal from "./modals/ContentModal.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Content(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsModalOpen = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setModalContent = match$1[1];
  var closeModal = function () {
    setIsModalOpen(function (param) {
          return false;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: Belt_Array.map(WorkersData.data, (function (worker) {
                              var name = worker.nomComplet;
                              var sector = worker.secteurActivite;
                              var city = worker.villeDeResidence;
                              var rating = worker.nombreEtoile;
                              var image = worker.image;
                              return JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("img", {
                                                  className: "w-full h-48 object-cover",
                                                  alt: "Travailleur",
                                                  src: image
                                                }),
                                            JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsx("h1", {
                                                          children: name,
                                                          className: "font-bold text-2xl mb-2 text-center"
                                                        }),
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx("i", {
                                                                  className: "fas fa-briefcase mr-2"
                                                                }),
                                                            sector
                                                          ],
                                                          className: "flex items-center justify-center text-gray-700 text-lg italic mb-2"
                                                        }),
                                                    JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx("i", {
                                                                  className: "fas fa-map-marker-alt mr-2"
                                                                }),
                                                            city
                                                          ],
                                                          className: "flex items-center justify-center text-gray-700 text-lg italic mb-2"
                                                        }),
                                                    JsxRuntime.jsx("div", {
                                                          children: "(" + rating + ")",
                                                          className: "flex items-center justify-center text-yellow-500 text-lg mb-2"
                                                        }),
                                                    JsxRuntime.jsx("div", {
                                                          children: JsxRuntime.jsx("button", {
                                                                children: "Voir détails",
                                                                className: "bg-indigo-600 text-white px-4 py-2 rounded",
                                                                onClick: (function (param) {
                                                                    var content = "Détails du travailleur";
                                                                    setModalContent(function (param) {
                                                                          return content;
                                                                        });
                                                                    setIsModalOpen(function (param) {
                                                                          return true;
                                                                        });
                                                                  })
                                                              }),
                                                          className: "flex justify-center mt-4"
                                                        })
                                                  ],
                                                  className: "px-6 py-4"
                                                })
                                          ],
                                          className: "rounded overflow-hidden shadow-lg hover:cursor-pointer p-6"
                                        });
                            })),
                      className: "p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5"
                    }),
                JsxRuntime.jsx(ContentModal.make, {
                      isOpen: match[0],
                      close: closeModal
                    })
              ],
              className: "py-4 px-4 pt-3.5 mt-0"
            });
}

var make = Content;

export {
  make ,
}
/* react Not a pure module */
