// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Base from "./layouts/Base.res.mjs";
import * as React from "react";
import * as LoginContext from "./LoginContext.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Signup(props) {
  var match = React.useState(function () {
        return "";
      });
  var setUsername = match[1];
  var username = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setEmail = match$1[1];
  var email = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPassword = match$2[1];
  var password = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setConfirmPassword = match$3[1];
  var confirmPassword = match$3[0];
  var match$4 = React.useState(function () {
        return "";
      });
  var setError = match$4[1];
  var error = match$4[0];
  React.useState(function () {
        return "";
      });
  var match$5 = LoginContext.useContext();
  var signup = match$5.signup;
  var validateForm = function () {
    if (password !== confirmPassword) {
      setError(function (param) {
            return "Les mots de passe ne correspondent pas.";
          });
      return false;
    } else if (username === "" || email === "" || password === "") {
      setError(function (param) {
            return "Tous les champs sont obligatoires.";
          });
      return false;
    } else {
      signup(email, password);
      RescriptReactRouter.push("/");
      setError(function (param) {
            return "";
          });
      return true;
    }
  };
  var handleSubmit = function ($$event) {
    $$event.preventDefault();
    if (validateForm()) {
      console.log("Inscription réussie");
      return RescriptReactRouter.push("/login");
    }
    
  };
  var tmp = error === "" ? null : JsxRuntime.jsx("p", {
          children: error,
          style: {
            color: "red"
          }
        });
  return JsxRuntime.jsx(Base.make, {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx("div", {
                          children: JsxRuntime.jsx("div", {
                                children: JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("h2", {
                                              children: "INSCRIPTION"
                                            }),
                                        tmp,
                                        JsxRuntime.jsxs("form", {
                                              children: [
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("label", {
                                                              children: "Nom d'utilisateur :"
                                                            }),
                                                        JsxRuntime.jsx("input", {
                                                              className: "block w-fill rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1",
                                                              required: true,
                                                              type: "text",
                                                              value: username,
                                                              onChange: (function (e) {
                                                                  setUsername(function (param) {
                                                                        return e.target.value;
                                                                      });
                                                                })
                                                            })
                                                      ]
                                                    }),
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("label", {
                                                              children: "Email :"
                                                            }),
                                                        JsxRuntime.jsx("input", {
                                                              className: "block w-fill rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1",
                                                              required: true,
                                                              type: "email",
                                                              value: email,
                                                              onChange: (function (e) {
                                                                  setEmail(function (param) {
                                                                        return e.target.value;
                                                                      });
                                                                })
                                                            })
                                                      ]
                                                    }),
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("label", {
                                                              children: "Mot de passe :"
                                                            }),
                                                        JsxRuntime.jsx("input", {
                                                              className: "block w-fill rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1",
                                                              required: true,
                                                              type: "password",
                                                              value: password,
                                                              onChange: (function (e) {
                                                                  setPassword(function (param) {
                                                                        return e.target.value;
                                                                      });
                                                                })
                                                            })
                                                      ]
                                                    }),
                                                JsxRuntime.jsxs("div", {
                                                      children: [
                                                        JsxRuntime.jsx("label", {
                                                              children: "Confirmer le mot de passe :"
                                                            }),
                                                        JsxRuntime.jsx("input", {
                                                              className: "block w-fill rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1",
                                                              required: true,
                                                              type: "password",
                                                              value: confirmPassword,
                                                              onChange: (function (e) {
                                                                  setConfirmPassword(function (param) {
                                                                        return e.target.value;
                                                                      });
                                                                })
                                                            })
                                                      ]
                                                    }),
                                                JsxRuntime.jsx("button", {
                                                      children: JsxRuntime.jsx("div", {
                                                            children: "S'inscrire",
                                                            style: {
                                                              backgroundColor: "#007BFF",
                                                              border: "none",
                                                              color: "white",
                                                              cursor: "pointer;",
                                                              marginTop: "10px",
                                                              padding: "10px 20px",
                                                              borderRadius: "5px"
                                                            }
                                                          }),
                                                      type: "submit"
                                                    })
                                              ],
                                              onSubmit: handleSubmit
                                            }),
                                        JsxRuntime.jsxs("p", {
                                              children: [
                                                "Avez-vous déjà un compte ? ",
                                                JsxRuntime.jsx("a", {
                                                      children: "Cliquez ici",
                                                      style: {
                                                        color: "#007BFF",
                                                        textDecoration: "none"
                                                      },
                                                      href: "/login"
                                                    }),
                                                " pour vous connecter"
                                              ]
                                            })
                                      ],
                                      style: {
                                        border: "1px solid #ccc;",
                                        margin: "0 auto",
                                        maxWidth: "400px",
                                        padding: "20px"
                                      }
                                    }),
                                style: {
                                  backgroundColor: "white",
                                  display: "flex",
                                  height: "95%",
                                  padding: "20px",
                                  width: "95%",
                                  borderRadius: "2px",
                                  boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
                                  alignItems: "center;",
                                  flexDirection: "column",
                                  justifyContent: "center"
                                }
                              }),
                          style: {
                            backgroundColor: "#007BFF",
                            display: "flex",
                            height: "400px",
                            width: "500px",
                            borderRadius: "2px;",
                            alignItems: "center",
                            justifyContent: "center"
                          }
                        }),
                    style: {
                      display: "flex",
                      height: "100vh;",
                      marginTop: "100px",
                      marginBottom: "100px",
                      alignItems: "center",
                      justifyContent: "center"
                    }
                  })
            });
}

var make = Signup;

export {
  make ,
}
/* Base Not a pure module */
