// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ContactModal from "../modals/ContactModal.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Base(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsModalOpen = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("nav", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsx("img", {
                                                        className: "h-8 w-auto",
                                                        alt: "Your Company",
                                                        src: "https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500"
                                                      }),
                                                  className: "flex flex-shrink-0 items-center"
                                                }),
                                            JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx("a", {
                                                                children: "Accueil",
                                                                className: "rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white",
                                                                href: "/"
                                                              }),
                                                          JsxRuntime.jsx("a", {
                                                                children: "Contact",
                                                                className: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white",
                                                                href: "#",
                                                                onClick: (function (param) {
                                                                    setIsModalOpen(function (param) {
                                                                          return true;
                                                                        });
                                                                  })
                                                              })
                                                        ],
                                                        className: "flex space-x-4"
                                                      }),
                                                  className: "hidden sm:ml-6 sm:block"
                                                })
                                          ],
                                          className: "flex items-center"
                                        }),
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("a", {
                                                  children: "Connexion",
                                                  className: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white",
                                                  href: "#"
                                                }),
                                            JsxRuntime.jsx("a", {
                                                  children: "Inscription",
                                                  className: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white",
                                                  href: "#"
                                                })
                                          ],
                                          className: "flex space-x-4 ml-auto"
                                        })
                                  ],
                                  className: "relative flex h-16 items-center justify-between"
                                }),
                            className: "mx-auto max-w-7xl px-2 sm:px-6 lg:px-8"
                          }),
                      className: "bg-gray-800 fixed top-0 left-0 right-0 z-50"
                    }),
                props.children,
                JsxRuntime.jsx(ContactModal.make, {
                      isOpen: match[0],
                      onClose: (function () {
                          setIsModalOpen(function (param) {
                                return false;
                              });
                        })
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h1", {
                                    children: "Une plateforme permettant de vous mettre en contact",
                                    className: "text-balance text-5xl font-semibold tracking-tight text-white sm:text-7xl"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "avec des travailleurs qualifiés, proche de chez vous.",
                                    className: "mt-8 text-pretty text-lg font-medium text-white sm:text-xl/8"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("a", {
                                            children: "Accueil",
                                            className: "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
                                            href: "/"
                                          }),
                                      JsxRuntime.jsxs("a", {
                                            children: [
                                              "Contact",
                                              JsxRuntime.jsx("span", {})
                                            ],
                                            className: "text-sm/6 font-semibold text-white",
                                            href: "#",
                                            onClick: (function (param) {
                                                setIsModalOpen(function (param) {
                                                      return true;
                                                    });
                                              })
                                          })
                                    ],
                                    className: "mt-10 flex items-center justify-center gap-x-6"
                                  })
                            ],
                            className: "text-center"
                          }),
                      className: "bg-gray-800 mx-auto max-w-1xl py-32 sm:py-48 lg:py-56"
                    })
              ]
            });
}

var make = Base;

export {
  make ,
}
/* react Not a pure module */
