// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var images = [
  "/img/1.jpg",
  "/img/2.jpg"
];

function Header(props) {
  var interval = props.interval;
  var match = React.useState(function () {
        return 0;
      });
  var setCurrentIndex = match[1];
  var currentIndex = match[0];
  React.useEffect((function () {
          var timer = setInterval((function () {
                  setCurrentIndex(function (currentIndex) {
                        return Caml_int32.mod_(currentIndex + 1 | 0, images.length);
                      });
                }), interval);
          return (function () {
                    clearInterval(timer);
                  });
        }), [currentIndex]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-full h-full object-cover",
                      alt: "Slider image",
                      src: Core__Option.getOr(images[currentIndex], "")
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("h1", {
                                    children: "Reserver un service",
                                    className: "text-balance text-5xl font-semibold tracking-tight text-gray-900 sm:text-7xl"
                                  }),
                              JsxRuntime.jsx("p", {
                                    children: "Reservez un service de qualite aupres de nos expert pour tout vos travaux a domicile",
                                    className: "mt-8 text-pretty text-lg font-medium sm:text-xl"
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("input", {
                                                        className: "block w-full rounded-l-md border-0 px-4 py-2 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm",
                                                        placeholder: "Rechercher"
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: "Rechercher",
                                                        className: "h-full px-4 py-2 bg-indigo-600 text-white rounded-r-md hover:bg-indigo-700 focus:outline-none"
                                                      })
                                                ],
                                                className: "relative mt-2 flex items-center"
                                              })
                                        }),
                                    className: "mb-80 mt-10 flex items-center justify-center gap-x-6"
                                  })
                            ],
                            className: "relative z-20 text-center"
                          }),
                      className: "absolute inset-20 flex flex-col justify-center items-center h-full"
                    })
              ],
              className: "slider relative"
            });
}

var make = Header;

export {
  images ,
  make ,
}
/* react Not a pure module */
